---

- name: Show platform
  debug:
    msg: "Running on: {{ ansible_distribution }} {{ ansible_major_distribution }} "

- name: Include distro specific vars
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Include os specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install java package(s)
  package:
    name: "{{ java_packages }}"
    state: present

- name: Set JAVA_HOME
  template:
    src: java_home.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home | length
