---

- name: Debug distro
  debug:
    var: ansible_distribution

- name: Debug distro major
  debug:
    var: ansible_distribution_major_version

- name: Check current java version
  command: java -version
  failed_when: no
  changed_when: no
  register: java_version

- name: Debug java_version
  debug:
    var: java_version

- name: Include distro specific vars
  include_vars: "{{ ansible_distribution }}-{{ ansible_distribution_major_version }}.yml"

- name: Debug java_packages
  debug:
    var: java_packages

- name: Include os specific tasks
  include_tasks: "{{ ansible_os_family }}.yml"

- name: Install packages
  package:
    name: "{{ java_packages }}"
    state: present



