---

dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: ${MOLECULE_IMAGE:-ghcr.io/tonyskidmore/ci-ubuntu2004-ansible:latest}
    # tmpfs:
    #   - /run
    #   - /tmp
    pre_build_image: true
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    privileged: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
