---

dependency:
  name: galaxy
driver:
  name: podman
platforms:
  - name: instance
    image: tonyskidmore/docker-${MOLECULE_DISTRO:-centos7-ansible}-ansible:latest
    # tmpfs:
    #   - /run
    #   - /tmp
    pre_build_image: true
    command: /sbin/init
    capabilities:
      - SYS_ADMIN
    privileged: false
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
provisioner:
  name: ansible
verifier:
  name: ansible
lint: |
  set -e
  yamllint .
  ansible-lint .
