---

- name: Verify
  hosts: all
  gather_facts: false

  tasks:

    - name: Check current java version
      command: java -version
      failed_when: no
      changed_when: no
      register: java_version

    - name: Debug java_version
      debug:
        var: java_version

    - name: Debug java_version
      debug:
        msg: "Installed java version: {{ java_version.stderr_lines[0] }}"

    - name: Check output contains 'openjdk version'
      assert:
        that: java_version.stderr_lines[0] is search("openjdk version")
