---
name: CI
'on':
  pull_request:
  push:
    branches:
      - main
  schedule:
    - cron: "0 4 * * 4"

defaults:
  run:
    working-directory: 'geerlingguy.php'

jobs:

  molecule:
    name: Molecule
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          # - distro: centos8
          #   playbook: converge.yml
          # - distro: centos7
          #   playbook: converge.yml
          - distro: ubuntu2004
          #  playbook: converge.yml
          # - distro: ubuntu1804
          #   playbook: converge.yml
          # - distro: debian10
          #   playbook: converge.yml
          # - distro: debian9
          #   playbook: converge.yml

          # - distro: centos7
          #   playbook: source-install.yml

    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2
        with:
          path: 'ansible-role-java'

      - name: Set up Python 3.
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Get podman version
        run: |
          command -v podman
          podman --version

      - name: Install test dependencies.
        run: |
          python3 -m pip install --upgrade pip
          python3 -m pip install --upgrade setuptools
          python3 -m pip install ansible==2.9.22 
          python3 -m pip install molecule[podman,lint]

      - name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
          MOLECULE_DISTRO: ${{ matrix.distro }}
          # MOLECULE_PLAYBOOK: ${{ matrix.playbook }}